name: github-release

on:
  workflow_dispatch:
    inputs:
      xcaddy_version:
        description: Version of xcaddy to use.
        default: v0.4.4 # renovate: datasource=github-releases depName=caddyserver/xcaddy versioning=semver
        required: true
        type: string
      caddy_version:
        description: Version of caddy to compile.
        default: v2.9.1 # renovate: datasource=github-releases depName=caddyserver/caddy versioning=semver
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: setup git config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: install cocogitto
        uses: oknozor/cocogitto-action@v3.9
        with:
          check: false

      - name: build caddy
        run: |
          #!/bin/bash
          set -eu

          ./build.sh "${{ inputs.caddy_version }}" "${{ inputs.xcaddy_version }}"

      - uses: softprops/action-gh-release@v2.2.1
        name: create release
        with:
          body: |
            For caddy changelogs look here: https://github.com/caddyserver/caddy/releases/tag/${{ inputs.caddy_version }}
          tag_name: ${{ inputs.caddy_version }}
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            dist/caddy_${{ inputs.caddy_version }}_darwin_amd64.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_darwin_arm64.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_linux_386.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_linux_amd64.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_linux_arm64.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_windows_386.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_windows_amd64.tar.gz
            dist/caddy_${{ inputs.caddy_version }}_windows_arm64.tar.gz
