name: github-release

on:
  workflow_dispatch:
    inputs:
      xcaddy_version:
        description: Version of xcaddy to use.
        default: v0.4.4 # renovate: datasource=github-releases depName=caddyserver/xcaddy versioning=semver
        required: true
        type: string
      caddy_version:
        description: Version of caddy to compile.
        default: v2.9.1 # renovate: datasource=github-releases depName=caddyserver/caddy versioning=semver
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install tar gzip

      - name: build caddy
        id: release
        run: |
          #!/bin/bash
          set -eu

          ./build.sh "${{ inputs.caddy_version }}" "${{ inputs.xcaddy_version }}"
          ls -la dist
          CADDY_VERSION=${{ inputs.caddy_version }}
          TRIMMED_VERSION=${CADDY_VERSION:1}
          echo "version=$TRIMMED_VERSION" >> $GITHUB_OUTPUT

      - uses: softprops/action-gh-release@v2.2.1
        name: create release
        with:
          body: |
            For caddy changelogs look here: https://github.com/caddyserver/caddy/releases/tag/${{ inputs.caddy_version }}
          tag_name: ${{ inputs.caddy_version }}
          token: ${{ secrets.RELEASE_TOKEN }}
          fail_on_unmatched_files: true
          files: |
            dist/caddy-${{ steps.release.outputs.version }}-checksums.txt
            dist/caddy-${{ steps.release.outputs.version }}-darwin-amd64.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-darwin-arm64.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-linux-386.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-linux-amd64.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-linux-arm64.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-windows-386.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-windows-amd64.tar.gz
            dist/caddy-${{ steps.release.outputs.version }}-windows-arm64.tar.gz
